spring.application.name=ms-prioridades
server.port=8083
spring.datasource.url=jdbc:mariadb://localhost:3306/strix_msprioridades
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
strix.ms-usuarios.url=http://localhost:8081
strix.ms-tickets.url=http://localhost:8084
strix.ms-categorias.url=http://localhost:8082
strix.ms-prioridades.url=http://localhost:8083
