spring.application.name=ms-historial
server.port=8086
spring.datasource.url=jdbc:mariadb://localhost:3306/strix_mshistorial
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Dialecto Hibernate para MariaDB 10.4
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
